import {loadState,saveState,exportBackup,parseBackup,storageKey} from './storage.js';
import { $, $$, esc, uid, today, timeNow, formatDate, validPhone, normalizePhone, csv, download, templateFill, toast, confirmDialog, getClassList, groupCount } from './utils.js';
import {detectIntegrations,importExternalStudents,importExternalMetrics,integrationKeys} from './integrations.js';

const state=loadState();
const app={route:location.hash.replace(/^#/,'')||'dashboard',locked:false,composerDraft:null};
const messageTypes=["General Announcement","Homework","Exam Reminder","Result Update","Fee Reminder","Attendance Alert","Low Attendance Warning","Achievement","Birthday","Parent Meeting","Important Notice","Custom Message"];
const nav=[
 {sec:"Workspace",items:[['dashboard','⌂','Dashboard'],['students','◉','Students'],['parents','👪','Parents'],['composer','✉','Message Composer'],['history','◷','Communication History'],['followups','✓','Follow-ups']]},
 {sec:"Engagement",items:[['announcements','📢','Announcements'],['directory','☎','Parent Directory'],['reminders','⏰','Scheduled Reminders'],['templates','▦','Smart Templates']]},
 {sec:"Insights",items:[['analytics','▥','Analytics'],['reports','▤','Reports']]},
 {sec:"System",items:[['integrations','↔','Manager Integrations'],['backup','◫','Backup & Restore'],['settings','⚙','Settings']]}
];
const routes={dashboard:dashboard,students:students,parents:parents,composer:composer,history:history,followups:followups,announcements:announcements,directory:directory,reminders:reminders,templates:templates,analytics:analytics,reports:reports,integrations:integrations,backup:backup,settings:settings};

function save(){saveState(state)}
function parentOf(student){return state.parents.find(p=>p.id===student?.parentId)}
function studentOf(id){return state.students.find(s=>s.id===id)}
function communicationContext(student,parent,extra={}){return {studentName:student?.name||'',parentName:parent?.name||'',class:student?.className||'',date:extra.date||today(),time:extra.time||timeNow(),amount:student?.pendingFee??'',dueDate:student?.dueDate||'',attendance:student?.attendance??'',percentage:student?.percentage??'',grade:student?.grade||'',teacherName:state.settings.teacherName||'Teacher',coachingName:state.settings.coachingName||'',message:extra.message||''}}
function cleanPhone(p){return normalizePhone(p,state.settings.phoneCountry||'91')}
function page(title,sub,body,actions=''){return `<div class="content"><div class="page-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="page-actions no-print">${actions}</div></div>${body}</div>`}
function stat(label,value,icon,note){return `<div class="card stat-card"><div class="eyebrow">${label}</div><div class="value">${value}</div><div class="delta">${note||'Live local data'}</div><div class="stat-icon">${icon}</div></div>`}
function feature(title,desc,icon,route){return `<div class="card feature-card"><div><div class="feature-icon">${icon}</div><h4>${title}</h4><p>${desc}</p></div><button class="btn btn-ghost btn-small no-print" data-route="${route}">Open</button></div>`}
function setView(html,title){$('#view').innerHTML=html;$('#pageTitle').textContent=title}
function renderShell(){
 $('#sidebar').innerHTML=`<div class="brand"><div class="brand-mark">PC</div><div><strong>Parent Communication</strong><small>Manager Pro v2</small></div></div><div class="nav">${nav.map(g=>`<div class="nav-section">${g.sec}</div>${g.items.map(n=>`<a href="#${n[0]}" class="nav-item" data-route="${n[0]}"><span>${n[1]}</span><span>${n[2]}</span></a>`).join('')}`).join('')}</div><div class="sidebar-footer"><div class="side-mini"><b>${state.settings.coachingName||'Parent Communication Manager Pro'}</b><br><span>${state.students.length} students · ${state.parents.length} parents</span></div><button class="btn btn-ghost" id="lockBtn">🔒 Lock App</button></div>`;
 $('#liveClock').textContent=new Date().toLocaleString();
 $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
 $('#themeToggle').onclick=toggleTheme;
 $('#lockBtn').onclick=lock;
 if(state.settings.pin) $('#lockBtn').textContent='🔒 Lock App';
}
function route(r){app.route=routes[r]?r:'dashboard';location.hash=app.route;$('#sidebar').classList.remove('open');renderNav();routes[app.route]();}
function renderNav(){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===app.route))}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();route(r.dataset.route);return}const a=e.target.closest('[data-action]');if(a){const fn=actions[a.dataset.action];if(fn)fn(a.dataset.id)}});
window.addEventListener('hashchange',()=>route(location.hash.replace(/^#/,'')||'dashboard'));
setInterval(()=>{const c=$('#liveClock');if(c)c.textContent=new Date().toLocaleString()},1000);

function dashboard(){
 const month=new Date().toISOString().slice(0,7),monthCom=state.communications.filter(x=>x.date?.startsWith(month)).length;
 const low=state.students.filter(s=>Number(s.attendance)>0&&Number(s.attendance)<75).length;
 const dues=state.students.filter(s=>Number(s.pendingFee)>0).length;
 const pending=state.followups.filter(x=>!x.completed).length;
 const recent=state.communications.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,5);
 setView(page('Dashboard','A premium communication workspace for fast, organized parent engagement.',`
 <div class="hero"><h2>Communicate clearly. Follow up confidently.</h2><p>Prepare personalized messages, send them to WhatsApp, track every conversation, manage follow-ups and keep parent data organized — all in a free, local-first app.</p><div class="hero-actions"><button class="btn" data-route="composer">✉ Compose Message</button><button class="btn" data-route="students">＋ Add Student</button><button class="btn" data-route="backup">↥ Backup Data</button></div></div><br>
 <div class="grid grid-4">${stat('Students',state.students.length,'👨‍🎓')}${stat('Parents',state.parents.length,'👪')}${stat('This Month',monthCom,'✉')}${stat('Pending Follow-ups',pending,'✓')}</div><br>
 <div class="grid grid-3"><div class="card"><div class="card-head"><h3>Smart Alerts</h3></div><div class="list"><div class="list-item"><span>Low attendance</span><b class="${low?'warning-text':''}">${low}</b></div><div class="list-item"><span>Pending fees</span><b class="${dues?'warning-text':''}">${dues}</b></div><div class="list-item"><span>Follow-ups due</span><b>${state.followups.filter(f=>!f.completed&&f.date<=today()).length}</b></div></div></div><div class="card"><div class="card-head"><h3>Manager Connections</h3><span class="badge success">Non-destructive</span></div><div class="list"><div class="list-item"><span>Students bridge</span><b>${detectIntegrations().students.detected?'Detected':'Not detected'}</b></div><div class="list-item"><span>Attendance</span><b>${detectIntegrations().attendance.detected?'Detected':'Optional'}</b></div><div class="list-item"><span>Results / Fees</span><b>${detectIntegrations().results.detected||detectIntegrations().fees.detected?'Detected':'Optional'}</b></div></div></div><div class="card"><div class="card-head"><h3>Quick Links</h3></div><div class="toolbar"><button class="btn btn-ghost btn-small" data-route="templates">Templates</button><button class="btn btn-ghost btn-small" data-route="analytics">Analytics</button><button class="btn btn-ghost btn-small" data-route="reports">Reports</button></div><p class="subtle">Your records stay in this browser by default.</p></div></div><br>
 <div class="grid grid-2"><div class="card"><div class="card-head"><h3>Recent Communications</h3><button class="btn btn-ghost btn-small" data-route="history">View all</button></div>${recent.length?`<div class="table-wrap"><table class="table"><tr><th>Date</th><th>Student</th><th>Type</th><th>Parent</th></tr>${recent.map(x=>`<tr><td>${formatDate(x.date)}</td><td>${esc(x.studentName)}</td><td><span class="badge">${esc(x.type)}</span></td><td>${esc(x.parentName)}</td></tr>`).join('')}</table></div>`:`<div class="empty"><div class="empty-icon">✉</div>No communication history yet.</div>`}</div>
 <div class="card"><div class="card-head"><h3>Premium Features</h3><span class="badge">v2</span></div><div class="grid grid-2">${feature('Smart Composer','Templates, dynamic student variables, preview and copy/share workflow.','✉','composer')}${feature('Follow-up Manager','Pending, completed, due-date and reschedule tracking.','✓','followups')}${feature('Analytics','Monthly, type-wise, class-wise and student-wise insights.','▥','analytics')}${feature('Backup & Restore','Versioned JSON backup and CSV exports.','◫','backup')}</div></div></div>`,'', 'Dashboard');
}

function students(){
 setView(page('Students','Student database, IDs, parent links and communication-ready records.','<div class="toolbar no-print"><input id="studentQ" class="input" placeholder="Search by name, ID or class"><select id="studentClass" class="select"><option value="">All classes</option>'+getClassList(state.students).map(c=>`<option>${esc(c)}</option>`).join('')+'</select><button class="btn btn-primary" data-action="studentModal">＋ Add Student</button><button class="btn btn-ghost" data-action="importStudents">↥ Import Existing Students</button><button class="btn btn-ghost" data-action="exportStudents">CSV</button></div><div id="studentTable" class="card"></div>'),'Students');
 const draw=()=>{const q=($('#studentQ').value||'').toLowerCase(),c=$('#studentClass').value;const rows=state.students.filter(s=>(`${s.name} ${s.studentId} ${s.className}`).toLowerCase().includes(q)&&(!c||s.className===c));$('#studentTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><tr><th>Student ID</th><th>Student</th><th>Class</th><th>Parent</th><th>Attendance</th><th>Result</th><th>Fee Due</th><th>Actions</th></tr>${rows.map(s=>{const p=parentOf(s);return `<tr><td><span class="badge">${esc(s.studentId)}</span></td><td><b>${esc(s.name)}</b><div class="subtle">${esc(s.rollNo||'')}</div></td><td>${esc(s.className||'—')}</td><td>${esc(p?.name||'—')}</td><td><span class="badge ${Number(s.attendance)<75&&Number(s.attendance)>0?'warning':''}">${s.attendance||0}%</span></td><td>${s.percentage||0}% ${s.grade?`· ${esc(s.grade)}`:''}</td><td>₹${Number(s.pendingFee||0).toLocaleString('en-IN')}</td><td><div class="actions"><button class="btn btn-ghost btn-small" data-action="studentModal" data-id="${s.id}">Edit</button><button class="btn btn-ghost btn-small" data-action="composeForStudent" data-id="${s.id}">Message</button><button class="btn btn-danger btn-small" data-action="deleteStudent" data-id="${s.id}">Delete</button></div></td></tr>`}).join('')}</table></div>`:'<div class="empty"><div class="empty-icon">👨‍🎓</div>No students found.</div>'};draw();$('#studentQ').oninput=draw;$('#studentClass').onchange=draw;
}
function parents(){
 setView(page('Parents','Parent database with phone validation, student relationships and quick communication.','<div class="toolbar no-print"><input id="parentQ" class="input" placeholder="Search parent, phone or email"><button class="btn btn-primary" data-action="parentModal">＋ Add Parent</button><button class="btn btn-ghost" data-action="exportParents">CSV</button></div><div id="parentTable" class="card"></div>'),'Parents');
 const draw=()=>{const q=($('#parentQ').value||'').toLowerCase();const rows=state.parents.filter(p=>(`${p.name} ${p.phone} ${p.email}`).toLowerCase().includes(q));$('#parentTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><tr><th>Parent</th><th>Phone</th><th>Email</th><th>Students</th><th>Actions</th></tr>${rows.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="subtle">${esc(p.address||'')}</div></td><td>${esc(p.phone)}</td><td>${esc(p.email||'—')}</td><td>${state.students.filter(s=>s.parentId===p.id).map(s=>esc(s.name)).join(', ')||'—'}</td><td><div class="actions"><button class="btn btn-ghost btn-small" data-action="parentModal" data-id="${p.id}">Edit</button><button class="btn btn-ghost btn-small" data-action="quickWhatsAppParent" data-id="${p.id}">WhatsApp</button><button class="btn btn-danger btn-small" data-action="deleteParent" data-id="${p.id}">Delete</button></div></td></tr>`).join('')}</table></div>`:'<div class="empty"><div class="empty-icon">👪</div>No parents found.</div>'};draw();$('#parentQ').oninput=draw;
}

function composer(){
 const types=messageTypes;const s=studentOf(app.composerDraft?.studentId),parent=parentOf(s||{});const temp=state.templates[0];
 setView(page('Message Composer','Personalize a message, preview it, then copy or open WhatsApp with the message pre-filled.','<div class="message-layout"><div class="card"><div class="form-row"><div class="field"><label class="label">Student</label><select id="cStudent" class="select"><option value="">Select student</option>'+state.students.map(x=>`<option value="${x.id}" ${x.id===app.composerDraft?.studentId?'selected':''}>${esc(x.name)} — ${esc(x.className)}</option>`).join('')+'</select></div><div class="field"><label class="label">Parent</label><select id="cParent" class="select"><option value="">Select parent</option>'+state.parents.map(x=>`<option value="${x.id}" ${x.id===parent?.id?'selected':''}>${esc(x.name)} — ${esc(x.phone)}</option>`).join('')+'</select></div></div><div class="form-row"><div class="field"><label class="label">Message type</label><select id="cType" class="select">'+types.map(t=>`<option>${t}</option>`).join('')+'</select></div><div class="field"><label class="label">Template</label><select id="cTemplate" class="select"><option value="">Blank / custom</option>${state.templates.map(t=>`<option value="${t.id}" ${temp&&t.id===temp.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div></div><div class="field"><label class="label">Message <span id="cCounter">0/2000</span></label><textarea id="cMessage" class="textarea" maxlength="2000" placeholder="Write your message..."></textarea></div><div class="toolbar no-print"><button class="btn btn-primary" data-action="saveCommunication">Save to History</button><button class="btn btn-ghost" data-action="copyComposer">Copy</button><button class="btn btn-ghost" data-action="whatsappComposer">WhatsApp</button><button class="btn btn-ghost" data-action="clearComposer">Clear</button><button class="btn btn-ghost" data-action="scheduleFromComposer">Schedule</button></div></div><div class="card"><div class="card-head"><h3>Live Preview</h3><span class="badge success">Personalized</span></div><div id="cPreview" class="preview">Select a student and enter a message.</div><br><div class="notice">Variables: {{studentName}}, {{parentName}}, {{class}}, {{date}}, {{time}}, {{amount}}, {{dueDate}}, {{attendance}}, {{percentage}}, {{grade}}, {{teacherName}}, {{message}}</div><br><div class="card-head"><h3>Template shortcuts</h3></div><div class="template-list">${state.templates.slice(0,8).map(t=>`<button class="template-chip" data-action="useTemplate" data-id="${t.id}">${esc(t.name)}</button>`).join('')}</div></div></div>'),'Message Composer');
 const init=()=>{const st=studentOf($('#cStudent').value),p=state.parents.find(x=>x.id===$('#cParent').value);const raw=$('#cMessage').value;const text=templateFill(raw,communicationContext(st,p,{message:raw}));$('#cPreview').textContent=text||'Select a student and enter a message.';$('#cCounter').textContent=`${raw.length}/2000`};
 $('#cStudent').onchange=()=>{const s=studentOf($('#cStudent').value);if(s?.parentId)$('#cParent').value=s.parentId;init()};$('#cParent').onchange=init;$('#cMessage').oninput=init;$('#cTemplate').onchange=()=>{const t=state.templates.find(x=>x.id===$('#cTemplate').value);if(t){$('#cMessage').value=t.body;init()}};init();
}
function history(){
 setView(page('Communication History','Every saved communication, searchable by student, parent, date or type.','<div class="toolbar no-print"><input id="hQ" class="input" placeholder="Search message history"><input id="hDate" class="input" type="date"><select id="hType" class="select"><option value="">All types</option>'+[...new Set(state.communications.map(x=>x.type))].map(x=>`<option>${esc(x)}</option>`).join('')+'</select><button class="btn btn-ghost" data-action="exportHistory">CSV</button><button class="btn btn-ghost" data-action="print">Print</button></div><div id="historyTable" class="card"></div>'),'Communication History');
 const draw=()=>{const q=($('#hQ').value||'').toLowerCase(),d=$('#hDate').value,t=$('#hType').value;const rows=state.communications.filter(x=>(`${x.studentName} ${x.parentName} ${x.message} ${x.type}`).toLowerCase().includes(q)&&(!d||x.date===d)&&(!t||x.type===t)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#historyTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><tr><th>Date</th><th>Student</th><th>Parent</th><th>Type</th><th>Message</th><th></th></tr>${rows.map(x=>`<tr><td>${formatDate(x.date)}</td><td>${esc(x.studentName)}</td><td>${esc(x.parentName)}</td><td><span class="badge">${esc(x.type)}</span></td><td>${esc(x.message).slice(0,140)}${x.message.length>140?'…':''}</td><td><button class="btn btn-danger btn-small" data-action="deleteCommunication" data-id="${x.id}">Delete</button></td></tr>`).join('')}</table></div>`:'<div class="empty"><div class="empty-icon">◷</div>No matching history.</div>'};draw();['hQ','hDate','hType'].forEach(id=>$('#'+id).oninput=draw);$('#hType').onchange=draw;
}
function followups(){
 const pending=state.followups.filter(x=>!x.completed).sort((a,b)=>a.date.localeCompare(b.date));
 setView(page('Follow-up Manager','Track pending conversations, notes, completion and rescheduling.','<div class="toolbar no-print"><button class="btn btn-primary" data-action="followupModal">＋ Create Follow-up</button><button class="btn btn-ghost" data-action="printFollowups">Print Report</button></div><div class="grid grid-2"><div class="card"><div class="card-head"><h3>Pending</h3><span class="badge warning">'+pending.length+'</span></div>${pending.length?`<div class="list">${pending.map(f=>`<div class="list-item"><div><b>${esc(f.studentName)}</b><div class="subtle">${formatDate(f.date)} · ${esc(f.note)}</div></div><div class="actions"><button class="btn btn-ghost btn-small" data-action="completeFollowup" data-id="${f.id}">Complete</button><button class="btn btn-ghost btn-small" data-action="editFollowup" data-id="${f.id}">Reschedule</button><button class="btn btn-danger btn-small" data-action="deleteFollowup" data-id="${f.id}">Delete</button></div></div>`).join('')}</div>`:'<div class="empty">No pending follow-ups.</div>'}</div><div class="card"><div class="card-head"><h3>Completed</h3><span class="badge success">'+state.followups.filter(x=>x.completed).length+'</span></div>${state.followups.filter(x=>x.completed).length?`<div class="list">${state.followups.filter(x=>x.completed).slice().reverse().slice(0,10).map(f=>`<div class="list-item"><div><b>${esc(f.studentName)}</b><div class="subtle">${formatDate(f.date)} · ${esc(f.note)}</div></div><button class="btn btn-ghost btn-small" data-action="completeFollowup" data-id="${f.id}">Reopen</button></div>`).join('')}</div>`:'<div class="empty">No completed follow-ups yet.</div>'}</div></div>'),'Follow-ups');
}
function announcements(){
 setView(page('Announcements','Prepare class-wide or selected-student notices and preserve announcement history.','<div class="toolbar no-print"><button class="btn btn-primary" data-action="announcementModal">＋ Create Announcement</button></div><div class="card">'+(state.announcements.length?`<div class="table-wrap"><table class="table"><tr><th>Date</th><th>Title</th><th>Audience</th><th>Class</th><th>Message</th><th></th></tr>${state.announcements.slice().reverse().map(a=>`<tr><td>${formatDate(a.date)}</td><td><b>${esc(a.title)}</b></td><td>${esc(a.audience)}</td><td>${esc(a.className||'All')}</td><td>${esc(a.message).slice(0,120)}</td><td><div class="actions"><button class="btn btn-ghost btn-small" data-action="copyAnnouncement" data-id="${a.id}">Copy</button><button class="btn btn-danger btn-small" data-action="deleteAnnouncement" data-id="${a.id}">Delete</button></div></td></tr>`).join('')}</table></div>`:'<div class="empty"><div class="empty-icon">📢</div>No announcements yet.</div>')+'</div>'),'Announcements');
}
function directory(){
 const cards=state.parents.map(p=>{const ss=state.students.filter(s=>s.parentId===p.id);return `<div class="card"><div class="card-head"><div><h3>${esc(p.name)}</h3><div class="subtle">${esc(p.phone)}</div></div><span class="badge">${ss.length} student${ss.length===1?'':'s'}</span></div><div class="subtle">${esc(p.email||'No email')}</div><div style="margin-top:10px">${ss.map(s=>`<span class="badge">${esc(s.name)} · ${esc(s.className)}</span>`).join(' ')||'<span class="subtle">No linked student</span>'}</div><div class="toolbar no-print" style="margin-top:12px"><button class="btn btn-primary btn-small" data-action="quickWhatsAppParent" data-id="${p.id}">WhatsApp</button><button class="btn btn-ghost btn-small" data-action="parentHistory" data-id="${p.id}">History</button><button class="btn btn-ghost btn-small" data-action="printDirectory">Print</button></div></div>`}).join('');
 setView(page('Parent Directory','Quick-contact directory with parent profiles and student relationships.','<div class="toolbar no-print"><input id="dirQ" class="input" placeholder="Search directory"><button class="btn btn-ghost" data-action="printDirectory">Print A4</button></div><div id="dirGrid" class="grid grid-3">'+(cards||'<div class="empty">No parents added.</div>')+'</div>'),'Parent Directory');
 const all=$$('#dirGrid .card');$('#dirQ').oninput=()=>{const q=$('#dirQ').value.toLowerCase();all.forEach(c=>c.classList.toggle('hidden',!c.textContent.toLowerCase().includes(q)))};
}
function reminders(){
 const upcoming=state.reminders.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 setView(page('Scheduled Reminders','Local scheduled message list. The app can surface due reminders while it is open.','<div class="toolbar no-print"><button class="btn btn-primary" data-action="reminderModal">＋ Schedule Message</button><button class="btn btn-ghost" data-action="requestNotifications">Enable Notifications</button></div><div class="card">'+(upcoming.length?`<div class="table-wrap"><table class="table"><tr><th>Date</th><th>Time</th><th>Student</th><th>Message</th><th>Status</th><th></th></tr>${upcoming.map(r=>`<tr><td>${formatDate(r.date)}</td><td>${r.time}</td><td>${esc(r.studentName)}</td><td>${esc(r.message)}</td><td><span class="badge ${r.date<today()?'danger':r.date===today()?'warning':'success'}">${r.date<today()?'Overdue':r.date===today()?'Due today':'Upcoming'}</span></td><td><button class="btn btn-danger btn-small" data-action="deleteReminder" data-id="${r.id}">Delete</button></td></tr>`).join('')}</table></div>`:'<div class="empty"><div class="empty-icon">⏰</div>No scheduled reminders.</div>')+'</div>'),'Scheduled Reminders');
}
function templates(){
 setView(page('Smart Templates','Create reusable messages with dynamic variables and preview-safe personalization.','<div class="toolbar no-print"><button class="btn btn-primary" data-action="templateModal">＋ Create Template</button><span class="notice">Use variables like {{studentName}}, {{parentName}}, {{class}}, {{amount}}, {{attendance}}.</span></div><div class="grid grid-2">'+state.templates.map(t=>`<div class="card"><div class="card-head"><h3>${esc(t.name)}</h3><span class="badge ${t.default?'success':''}">${t.default?'Default':'Custom'}</span></div><div class="preview">${esc(t.body)}</div><div class="actions no-print" style="margin-top:10px"><button class="btn btn-ghost btn-small" data-action="templateModal" data-id="${t.id}">Edit</button><button class="btn btn-danger btn-small" data-action="deleteTemplate" data-id="${t.id}">${t.default?'Reset':'Delete'}</button></div></div>`).join('')+'</div>'),'Smart Templates');
}
function analytics(){
 const total=state.communications.length,month=new Date().toISOString().slice(0,7),monthC=state.communications.filter(x=>x.date?.startsWith(month)).length;
 const types=groupCount(state.communications,'type'),classes={};state.communications.forEach(c=>{const s=studentOf(c.studentId);const k=s?.className||'Unknown';classes[k]=(classes[k]||0)+1});const maxType=Math.max(1,...Object.values(types)),maxClass=Math.max(1,...Object.values(classes));
 const low=state.students.filter(s=>Number(s.attendance)>0&&Number(s.attendance)<75).length,fees=state.students.filter(s=>Number(s.pendingFee)>0).length;
 setView(page('Analytics','Understand communication volume, follow-up load, attendance and fee alert signals.','<div class="grid grid-4">'+stat('Total Communications',total,'✉')+stat('This Month',monthC,'◷')+stat('Pending Follow-ups',state.followups.filter(x=>!x.completed).length,'✓')+stat('Low Attendance',low,'!','Students below 75%')+'</div><br><div class="grid grid-2"><div class="card"><div class="card-head"><h3>Message Type Statistics</h3></div>'+Object.entries(types).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="margin:12px 0"><div class="list-item"><span>${esc(k)}</span><b>${v}</b></div><div class="bar"><i style="width:${v/maxType*100}%"></i></div></div>`).join('')||'<div class="empty">No communication data.</div>'+'</div><div class="card"><div class="card-head"><h3>Class-wise Statistics</h3></div>'+Object.entries(classes).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="margin:12px 0"><div class="list-item"><span>Class ${esc(k)}</span><b>${v}</b></div><div class="bar"><i style="width:${v/maxClass*100}%"></i></div></div>`).join('')||'<div class="empty">No class-wise data.</div>'+'</div></div><br><div class="grid grid-3"><div class="card"><h3>Attendance Signal</h3><p class="muted">${low} student(s) below 75% attendance.</p><button class="btn btn-ghost btn-small" data-action="generateLowAttendance">Generate Messages</button></div><div class="card"><h3>Fee Signal</h3><p class="muted">${fees} student(s) currently have pending fee.</p><button class="btn btn-ghost btn-small" data-action="generateFeeReminders">Prepare Fee Reminders</button></div><div class="card"><h3>Follow-up Completion</h3><p class="muted">${state.followups.filter(x=>x.completed).length} of ${state.followups.length} completed.</p><div class="bar"><i style="width:${state.followups.length?state.followups.filter(x=>x.completed).length/state.followups.length*100:0}%"></i></div></div></div>'),'Analytics');
}
function reports(){
 const month=new Date().toISOString().slice(0,7),mc=state.communications.filter(x=>x.date?.startsWith(month));
 setView(page('Reports & Printing','A4-friendly reports with print preview using your browser print dialog.','<div class="grid grid-3"><div class="card"><h3>Parent Directory</h3><p class="muted">Parent contact list with student relationships.</p><button class="btn btn-primary" data-action="printDirectory">Print A4</button></div><div class="card"><h3>Communication History</h3><p class="muted">Print current history filters.</p><button class="btn btn-primary" data-route="history">Open History</button></div><div class="card"><h3>Monthly Communication Report</h3><p class="muted">'+mc.length+' communication(s) this month.</p><button class="btn btn-primary" data-action="printMonthly">Print A4</button></div><div class="card"><h3>Follow-up Report</h3><p class="muted">'+state.followups.length+' follow-up record(s).</p><button class="btn btn-primary" data-action="printFollowups">Print A4</button></div><div class="card"><h3>Student Data</h3><p class="muted">Export a CSV snapshot of student records.</p><button class="btn btn-ghost" data-action="exportStudents">Export CSV</button></div><div class="card"><h3>Communication Data</h3><p class="muted">Export communication history as CSV.</p><button class="btn btn-ghost" data-action="exportHistory">Export CSV</button></div></div>'),'Reports & Printing');
}
function integrations(){
 const d=detectIntegrations();
 setView(page('Manager Integrations','Connect Attendance Manager, Result Manager and Fee Manager without overwriting their data.','<div class="notice">This module is intentionally additive. It uses separate ParentComm storage and only reads compatible local browser data when found.</div><br><div class="grid grid-3">'+[['students','Students Bridge','ezee_students / students'],['attendance','Attendance Manager','ezee_attendance / attendanceData'],['results','Result Manager','ezee_results / resultData'],['fees','Fee Manager','ezee_fees / feeData']].map(([k,title,keys])=>`<div class="card"><div class="card-head"><h3>${title}</h3><span class="badge ${d[k].detected?'success':''}">${d[k].detected?'Detected':'Not detected'}</span></div><p class="muted">Keys checked: ${keys}</p><p>${d[k].detected?`${d[k].count} record(s) found in <b>${esc(d[k].key)}</b>`:'No compatible data found yet.'}</p></div>`).join('')+'</div><br><div class="card"><div class="card-head"><h3>Sync Actions</h3></div><div class="toolbar no-print"><button class="btn btn-primary" data-action="syncStudents">Import Students</button><button class="btn btn-ghost" data-action="syncMetrics">Sync Attendance / Results / Fees</button><button class="btn btn-ghost" data-action="recheckIntegrations">Re-check Sources</button></div><p class="subtle">Supported metrics are matched by Student ID, admission number or student name where available.</p></div>'),'Manager Integrations');
}
function backup(){
 setView(page('Backup & Restore','Protect your work with versioned JSON backups and portable CSV exports.','<div class="grid grid-2"><div class="card"><div class="card-head"><h3>JSON Backup</h3><span class="badge success">Version 2</span></div><p class="muted">Contains students, parents, messages, follow-ups, templates, reminders, settings and integration snapshots.</p><button class="btn btn-primary" data-action="exportJSON">Export Full Backup</button></div><div class="card"><div class="card-head"><h3>Import Backup</h3><span class="badge">Validated</span></div><p class="muted">The file is parsed and validated before replacing current app data.</p><input id="backupFile" type="file" accept=".json,application/json" class="input"><br><br><button class="btn btn-primary" data-action="importJSON">Restore Selected File</button></div></div><br><div class="card"><div class="card-head"><h3>CSV Exports</h3></div><div class="toolbar"><button class="btn btn-ghost" data-action="exportStudents">Students</button><button class="btn btn-ghost" data-action="exportParents">Parents</button><button class="btn btn-ghost" data-action="exportHistory">Communication History</button><button class="btn btn-ghost" data-action="exportFollowups">Follow-ups</button></div></div><br><div class="card"><div class="card-head"><h3>Data Integrity</h3></div><div class="kpi-grid"><div class="kpi-box"><span class="subtle">Storage Key</span><b style="font-size:13px">${storageKey()}</b></div><div class="kpi-box"><span class="subtle">Schema</span><b>v2</b></div><div class="kpi-box"><span class="subtle">Updated</span><b style="font-size:13px">${new Date(state.meta.updatedAt).toLocaleString()}</b></div></div></div>'),'Backup & Restore');
}
function settings(){
 setView(page('Settings','Personalize the workspace and manage privacy controls.','<div class="grid grid-2"><div class="card"><h3>Workspace</h3><div class="field"><label class="label">Teacher name</label><input id="setTeacher" class="input" value="${esc(state.settings.teacherName)}"></div><div class="field"><label class="label">Coaching / institute name</label><input id="setCoaching" class="input" value="${esc(state.settings.coachingName)}"></div><div class="field"><label class="label">WhatsApp country code</label><input id="setCountry" class="input" inputmode="numeric" value="${esc(state.settings.phoneCountry)}"></div><button class="btn btn-primary" data-action="saveSettings">Save Settings</button></div><div class="card"><h3>PIN Lock</h3><p class="muted">This is a local UI lock. It is not server-side encryption.</p><div class="field"><label class="label">New PIN (4–8 digits)</label><input id="setPin" class="input" type="password" inputmode="numeric" maxlength="8"></div><div class="toolbar"><button class="btn btn-primary" data-action="savePin">Save PIN</button><button class="btn btn-danger" data-action="removePin">Remove PIN</button></div></div></div><br><div class="card"><h3>Privacy</h3><p class="muted">Parent Communication Manager Pro is local-first. Records are kept in your browser's localStorage. Export backups before clearing browser storage or changing devices.</p><div class="notice">Never store passwords, banking credentials or highly sensitive secrets in this app.</div></div>'),'Settings');
}

const actions={
 studentModal:id=>openStudentModal(studentOf(id)), parentModal:id=>openParentModal(state.parents.find(p=>p.id===id)), followupModal:()=>openFollowupModal(), editFollowup:id=>openFollowupModal(state.followups.find(f=>f.id===id)), announcementModal:()=>openAnnouncementModal(), templateModal:id=>openTemplateModal(state.templates.find(t=>t.id===id)), reminderModal:()=>openReminderModal(),
 composeForStudent:id=>{app.composerDraft={studentId:id};route('composer')},
 deleteStudent:id=>{if(!confirmDialog('Delete this student? Their communication history will remain.'))return;state.students=state.students.filter(s=>s.id!==id);save();toast('Student deleted','success');students()},
 deleteParent:id=>{if(!confirmDialog('Delete this parent? Student records will be unlinked but not deleted.'))return;state.parents=state.parents.filter(p=>p.id!==id);state.students.forEach(s=>{if(s.parentId===id)s.parentId='' });save();toast('Parent deleted','success');parents()},
 deleteCommunication:id=>{if(!confirmDialog('Delete this communication history record?'))return;state.communications=state.communications.filter(x=>x.id!==id);save();toast('History record deleted','success');history()},
 completeFollowup:id=>{const f=state.followups.find(x=>x.id===id);if(f){f.completed=!f.completed;save();toast(f.completed?'Follow-up completed':'Follow-up reopened','success');followups()}},
 deleteFollowup:id=>{if(!confirmDialog('Delete this follow-up?'))return;state.followups=state.followups.filter(x=>x.id!==id);save();toast('Follow-up deleted','success');followups()},
 deleteAnnouncement:id=>{if(!confirmDialog('Delete announcement history?'))return;state.announcements=state.announcements.filter(x=>x.id!==id);save();toast('Announcement deleted','success');announcements()},
 deleteTemplate:id=>{const t=state.templates.find(x=>x.id===id);if(!t)return;if(t.default){openTemplateResetModal(t)}else if(confirmDialog('Delete this custom template?')){state.templates=state.templates.filter(x=>x.id!==id);save();toast('Template deleted','success');templates()}},
 deleteReminder:id=>{if(!confirmDialog('Delete scheduled reminder?'))return;state.reminders=state.reminders.filter(x=>x.id!==id);save();toast('Reminder deleted','success');reminders()},
 useTemplate:id=>{const t=state.templates.find(x=>x.id===id);if(t&&$('#cMessage')){$('#cMessage').value=t.body;$('#cTemplate').value=t.id;$('#cMessage').dispatchEvent(new Event('input'))}},
 saveCommunication:()=>saveComposerCommunication(),copyComposer:()=>navigator.clipboard?.writeText($('#cPreview')?.textContent||'').then(()=>toast('Message copied','success')).catch(()=>toast('Copy blocked by browser','error')),
 whatsappComposer:()=>openComposerWhatsApp(),clearComposer:()=>{if($('#cMessage'))$('#cMessage').value='';$('#cMessage')?.dispatchEvent(new Event('input'))},scheduleFromComposer:()=>openReminderModalFromComposer(),
 copyAnnouncement:id=>{const a=state.announcements.find(x=>x.id===id);if(a)navigator.clipboard?.writeText(a.message).then(()=>toast('Announcement copied','success'))},quickWhatsAppParent:id=>{const p=state.parents.find(x=>x.id===id);if(p)window.open(`https://wa.me/${cleanPhone(p)}?text=${encodeURIComponent('Hello '+p.name+',')}`,'_blank')},parentHistory:id=>{app.parentHistoryId=id;route('history')},
 print:()=>window.print(),printDirectory:()=>printHtml(parentDirectoryHtml(),'Parent Directory'),printMonthly:()=>printHtml(monthlyReportHtml(),'Monthly Communication Report'),printFollowups:()=>printHtml(followupReportHtml(),'Follow-up Report'),
 exportStudents:()=>download('students.csv',csv(state.students),'text/csv'),exportParents:()=>download('parents.csv',csv(state.parents),'text/csv'),exportHistory:()=>download('communication-history.csv',csv(state.communications),'text/csv'),exportFollowups:()=>download('followups.csv',csv(state.followups),'text/csv'),exportJSON:()=>download('parent-communication-manager-v2-backup.json',exportBackup(state),'application/json'),
 importJSON:()=>importBackup(),importStudents:()=>{const r=importExternalStudents(state);save();toast(r.count?`Imported ${r.count} student(s) from ${r.key}`:'No compatible student source found',r.count?'success':'error');students()},syncStudents:()=>{const r=importExternalStudents(state);save();toast(r.count?`Imported ${r.count} student(s)`: 'No compatible student source found',r.count?'success':'error');integrations()},syncMetrics:()=>{const r=importExternalMetrics(state);save();toast(`Synced attendance ${r.updated.attendance}, results ${r.updated.results}, fees ${r.updated.fees}`,'success');integrations()},recheckIntegrations:()=>integrations(),requestNotifications:async()=>{if(!('Notification'in window)){toast('Notifications are not supported here','error');return}const p=await Notification.requestPermission();toast(`Notification permission: ${p}`,p==='granted'?'success':'error')},
 generateLowAttendance:()=>{app.autoType='Low Attendance Warning';route('composer');toast('Compose using Low Attendance Warning template','success')},generateFeeReminders:()=>{app.autoType='Fee Reminder';route('composer');toast('Compose using Fee Reminder template','success')},saveSettings:()=>{state.settings.teacherName=$('#setTeacher').value.trim()||'Teacher';state.settings.coachingName=$('#setCoaching').value.trim()||'Parent Communication Manager Pro';state.settings.phoneCountry=$('#setCountry').value.replace(/\D/g,'')||'91';save();renderShell();toast('Settings saved','success');settings()},savePin:()=>{const p=$('#setPin').value.trim();if(!/^\d{4,8}$/.test(p)){toast('PIN must be 4–8 digits','error');return}state.settings.pin=p;save();toast('PIN saved','success')},removePin:()=>{if(!confirmDialog('Remove app PIN lock?'))return;state.settings.pin='';save();toast('PIN removed','success')}
};

function openModal(title,body,onSave,saveLabel='Save'){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>${title}</h3>${body}<div class="modal-actions"><button class="btn btn-ghost" id="modalCancel">Cancel</button><button class="btn btn-primary" id="modalSave">${saveLabel}</button></div></div></div>`;$('#modalCancel').onclick=()=>root.innerHTML='';$('#modalSave').onclick=()=>{if(onSave()!==false)root.innerHTML=''};return root}
function openStudentModal(s){const editing=!!s;const body=`<div class="form-row"><div class="field"><label class="label">Student name</label><input id="mName" class="input" value="${esc(s?.name||'')}"></div><div class="field"><label class="label">Class</label><input id="mClass" class="input" value="${esc(s?.className||'')}"></div></div><div class="form-row"><div class="field"><label class="label">Roll / Admission No.</label><input id="mRoll" class="input" value="${esc(s?.rollNo||'')}"></div><div class="field"><label class="label">Parent</label><select id="mParent" class="select"><option value="">No parent</option>${state.parents.map(p=>`<option value="${p.id}" ${p.id===s?.parentId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div></div><div class="form-row-3"><div class="field"><label class="label">Attendance %</label><input id="mAttendance" class="input" type="number" min="0" max="100" value="${s?.attendance??0}"></div><div class="field"><label class="label">Result %</label><input id="mPercent" class="input" type="number" min="0" max="100" value="${s?.percentage??0}"></div><div class="field"><label class="label">Grade</label><input id="mGrade" class="input" value="${esc(s?.grade||'')}"></div></div><div class="form-row"><div class="field"><label class="label">Pending Fee</label><input id="mFee" class="input" type="number" min="0" value="${s?.pendingFee??0}"></div><div class="field"><label class="label">Fee Due Date</label><input id="mDue" class="input" type="date" value="${s?.dueDate||''}"></div></div>`;
 openModal(editing?'Edit Student':'Add Student',body,()=>{const name=$('#mName').value.trim(),cls=$('#mClass').value.trim();if(!name||!cls){toast('Name and class are required','error');return false}const x=s||{id:uid('stu'),studentId:`STU-${String(state.students.length+1).padStart(4,'0')}`};Object.assign(x,{name,className:cls,rollNo:$('#mRoll').value.trim(),parentId:$('#mParent').value,attendance:Number($('#mAttendance').value)||0,percentage:Number($('#mPercent').value)||0,grade:$('#mGrade').value.trim(),pendingFee:Number($('#mFee').value)||0,dueDate:$('#mDue').value});if(!s)state.students.push(x);save();students();toast(editing?'Student updated':'Student added','success')})}
function openParentModal(p){const editing=!!p;const body=`<div class="form-row"><div class="field"><label class="label">Parent name</label><input id="pmName" class="input" value="${esc(p?.name||'')}"></div><div class="field"><label class="label">Phone</label><input id="pmPhone" class="input" inputmode="tel" value="${esc(p?.phone||'')}"></div></div><div class="form-row"><div class="field"><label class="label">Email</label><input id="pmEmail" class="input" value="${esc(p?.email||'')}"></div><div class="field"><label class="label">Address</label><input id="pmAddress" class="input" value="${esc(p?.address||'')}"></div></div>`;openModal(editing?'Edit Parent':'Add Parent',body,()=>{const name=$('#pmName').value.trim(),phone=$('#pmPhone').value.trim();if(!name||!validPhone(phone)){toast('Enter parent name and a valid phone number','error');return false}const x=p||{id:uid('par')};Object.assign(x,{name,phone,email:$('#pmEmail').value.trim(),address:$('#pmAddress').value.trim()});if(!p)state.parents.push(x);save();parents();toast(editing?'Parent updated':'Parent added','success')})}
function openFollowupModal(f){const editing=!!f;const body=`<div class="form-row"><div class="field"><label class="label">Student</label><select id="fumStudent" class="select">${state.students.map(s=>`<option value="${s.id}" ${s.id===f?.studentId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label class="label">Follow-up date</label><input id="fumDate" class="input" type="date" value="${f?.date||today()}"></div></div><div class="field"><label class="label">Note</label><textarea id="fumNote" class="textarea">${esc(f?.note||'')}</textarea></div>`;openModal(editing?'Edit / Reschedule Follow-up':'Create Follow-up',body,()=>{const s=studentOf($('#fumStudent').value),note=$('#fumNote').value.trim();if(!s||!note){toast('Student and note are required','error');return false}if(f)Object.assign(f,{studentId:s.id,studentName:s.name,date:$('#fumDate').value,note});else state.followups.push({id:uid('fu'),studentId:s.id,studentName:s.name,date:$('#fumDate').value,note,completed:false,createdAt:Date.now()});save();followups();toast(editing?'Follow-up updated':'Follow-up created','success')})}
function openAnnouncementModal(){const body=`<div class="form-row"><div class="field"><label class="label">Title</label><input id="anmTitle" class="input"></div><div class="field"><label class="label">Class (optional)</label><select id="anmClass" class="select"><option value="">All Classes</option>${getClassList(state.students).map(c=>`<option>${esc(c)}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label class="label">Audience</label><select id="anmAudience" class="select"><option>All Parents</option><option>Selected Class</option><option>Selected Students</option></select></div><div class="field"><label class="label">Select students (optional)</label><select id="anmStudents" class="select" multiple size="4">${state.students.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(s.className)}</option>`).join('')}</select></div></div><div class="field"><label class="label">Announcement message</label><textarea id="anmMessage" class="textarea"></textarea></div>`;openModal('Create Announcement',body,()=>{const title=$('#anmTitle').value.trim(),msg=$('#anmMessage').value.trim(),students=[...$('#anmStudents').selectedOptions].map(x=>x.value);if(!title||!msg){toast('Title and message required','error');return false}state.announcements.push({id:uid('an'),date:today(),title,className:$('#anmClass').value,audience:$('#anmAudience').value,studentIds:students,message:msg});save();announcements();toast('Announcement saved','success')})}
function openTemplateModal(t){const editing=!!t;const body=`<div class="field"><label class="label">Template name</label><input id="tmName" class="input" value="${esc(t?.name||'')}"></div><div class="field"><label class="label">Template body</label><textarea id="tmBody" class="textarea">${esc(t?.body||'')}</textarea></div>`;openModal(editing?'Edit Template':'Create Template',body,()=>{const n=$('#tmName').value.trim(),b=$('#tmBody').value.trim();if(!n||!b){toast('Template name and body required','error');return false}if(t)Object.assign(t,{name:n,body:b});else state.templates.push({id:uid('tpl'),name:n,body:b,default:false,createdAt:Date.now()});save();templates();toast(editing?'Template updated':'Template created','success')})}
function openTemplateResetModal(t){openModal('Reset Default Template',`<p class="muted">This will restore the original default content for <b>${esc(t.name)}</b>.</p>`,()=>{const idx=state.templates.findIndex(x=>x.id===t.id);if(idx<0)return;const originals=["General Announcement","Homework","Exam Reminder","Result Update","Fee Reminder","Attendance Alert","Low Attendance Warning","Achievement","Birthday","Parent Meeting","Important Notice","Custom Message"];const bodies=["Dear {{parentName}},\nThis is to inform you regarding {{studentName}} of Class {{class}}.\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\n{{studentName}} has been assigned homework.\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nThis is a reminder regarding {{studentName}}'s upcoming examination.\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nHere is the result update for {{studentName}}.\nPercentage: {{percentage}}%\nGrade: {{grade}}\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nThis is a gentle reminder about the pending fee of ₹{{amount}} for {{studentName}}.\nDue date: {{dueDate}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\n{{studentName}}'s current attendance is {{attendance}}%.\nPlease help ensure regular attendance.\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\n{{studentName}}'s attendance is {{attendance}}%, which is below the preferred level.\nPlease contact us if any support is required.\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nCongratulations! {{studentName}} has achieved a wonderful milestone.\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nWishing {{studentName}} a very happy birthday! 🎉\nMay the year ahead be filled with joy and success.\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nA parent meeting is scheduled regarding {{studentName}}.\nDate: {{date}}\nTime: {{time}}\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\nImportant notice regarding {{studentName}}:\n\n{{message}}\n\nRegards,\n{{teacherName}}","Dear {{parentName}},\n\n{{message}}\n\nRegards,\n{{teacherName}}"];const i=originals.indexOf(t.name);t.body=bodies[i>=0?i:0];save();templates();toast('Default template reset','success')})}
function openReminderModal(r={},initial={}){const sId=r.studentId||initial.studentId||state.students[0]?.id||'';const body=`<div class="form-row-3"><div class="field"><label class="label">Student</label><select id="rmStudent" class="select">${state.students.map(s=>`<option value="${s.id}" ${s.id===sId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label class="label">Date</label><input id="rmDate" class="input" type="date" value="${r.date||initial.date||today()}"></div><div class="field"><label class="label">Time</label><input id="rmTime" class="input" type="time" value="${r.time||initial.time||'09:00'}"></div></div><div class="field"><label class="label">Message</label><textarea id="rmMsg" class="textarea">${esc(r.message||initial.message||'')}</textarea></div>`;openModal('Schedule Message',body,()=>{const s=studentOf($('#rmStudent').value),m=$('#rmMsg').value.trim();if(!s||!m){toast('Student and message required','error');return false}if(r.id)Object.assign(r,{studentId:s.id,studentName:s.name,date:$('#rmDate').value,time:$('#rmTime').value,message:m});else state.reminders.push({id:uid('rem'),studentId:s.id,studentName:s.name,date:$('#rmDate').value,time:$('#rmTime').value,message:m,createdAt:Date.now()});save();reminders();toast(r.id?'Reminder updated':'Reminder scheduled','success')})}
function openReminderModalFromComposer(){if(!$('#cStudent'))return;const s=studentOf($('#cStudent').value),p=state.parents.find(x=>x.id===$('#cParent').value);const raw=$('#cMessage').value;openReminderModal({}, {studentId:s?.id,date:today(),time:timeNow(),message:templateFill(raw,communicationContext(s,p,{message:raw}))})}
function saveComposerCommunication(){const s=studentOf($('#cStudent').value),p=state.parents.find(x=>x.id===$('#cParent').value),raw=$('#cMessage').value.trim(),type=$('#cType').value;if(!s||!p||!raw){toast('Select student, parent and write a message','error');return}const text=templateFill(raw,communicationContext(s,p,{message:raw}));state.communications.push({id:uid('com'),date:today(),createdAt:Date.now(),studentId:s.id,parentId:p.id,studentName:s.name,parentName:p.name,type,message:text,phone:p.phone});save();toast('Communication saved to history','success')}
function openComposerWhatsApp(){const s=studentOf($('#cStudent').value),p=state.parents.find(x=>x.id===$('#cParent').value),raw=$('#cMessage').value;if(!s||!p||!raw){toast('Select student, parent and message first','error');return}if(!validPhone(p.phone)){toast('Parent phone number is invalid','error');return}const text=templateFill(raw,communicationContext(s,p,{message:raw}));window.open(`https://wa.me/${cleanPhone(p)}?text=${encodeURIComponent(text)}`,'_blank')}
function importBackup(){const f=$('#backupFile')?.files?.[0];if(!f){toast('Choose a JSON backup file first','error');return}const r=new FileReader();r.onload=()=>{try{const next=parseBackup(r.result);if(!confirmDialog('Restore this backup? Current ParentComm data will be replaced.'))return;Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,next);save();renderShell();route('dashboard');toast('Backup restored successfully','success')}catch(e){toast('Backup failed validation','error')}};r.readAsText(f)}
function printHtml(html,title){const w=window.open('','_blank','noopener,noreferrer');if(!w){toast('Popup blocked. Allow popups to print.','error');return}w.document.write(`<!doctype html><html><head><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;padding:25px;color:#111}h1{font-size:20px;margin-bottom:15px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #bbb;padding:7px;text-align:left;vertical-align:top}th{background:#f1f5f9}.meta{font-size:10px;color:#555;margin-bottom:12px}@page{size:A4;margin:12mm}</style></head><body>${html}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function parentDirectoryHtml(){return `<h1>Parent Directory</h1><div class="meta">Generated ${new Date().toLocaleString()}</div><table><tr><th>Parent</th><th>Phone</th><th>Email</th><th>Students</th></tr>${state.parents.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.phone)}</td><td>${esc(p.email||'')}</td><td>${state.students.filter(s=>s.parentId===p.id).map(s=>`${esc(s.name)} (${esc(s.className)})`).join(', ')}</td></tr>`).join('')}</table>`}
function monthlyReportHtml(){const month=new Date().toISOString().slice(0,7),rows=state.communications.filter(x=>x.date?.startsWith(month));return `<h1>Monthly Communication Report</h1><div class="meta">Month: ${month} · Total: ${rows.length}</div><table><tr><th>Date</th><th>Student</th><th>Parent</th><th>Type</th><th>Message</th></tr>${rows.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.studentName)}</td><td>${esc(x.parentName)}</td><td>${esc(x.type)}</td><td>${esc(x.message)}</td></tr>`).join('')}</table>`}
function followupReportHtml(){return `<h1>Follow-up Report</h1><div class="meta">Generated ${new Date().toLocaleString()}</div><table><tr><th>Date</th><th>Student</th><th>Status</th><th>Note</th></tr>${state.followups.map(f=>`<tr><td>${esc(f.date)}</td><td>${esc(f.studentName)}</td><td>${f.completed?'Completed':'Pending'}</td><td>${esc(f.note)}</td></tr>`).join('')}</table>`}
function toggleTheme(){state.settings.theme=state.settings.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.settings.theme;save()}
function lock(){if(!state.settings.pin){toast('Set a PIN first in Settings','error');route('settings');return}$('#lockRoot').innerHTML=`<div class="lock-screen"><div class="lock-card"><h2>🔒 App Locked</h2><p class="muted">Enter your local PIN to continue.</p><input id="unlockPin" class="input" type="password" inputmode="numeric" maxlength="8"><br><br><button class="btn btn-primary" id="unlock">Unlock</button></div></div>`;$('#unlock').onclick=()=>{if($('#unlockPin').value===state.settings.pin){$('#lockRoot').innerHTML=''}else toast('Incorrect PIN','error')}}
async function reminderWatcher(){const now=new Date(),k=now.toISOString().slice(0,16).replace('T',' ');const key=`pcm_seen_${k}`;if(localStorage.getItem(key))return;const due=state.reminders.filter(r=>`${r.date} ${r.time}`<=k&&!r.notified).slice(0,3);for(const r of due){r.notified=true;try{if('Notification'in window&&Notification.permission==='granted')new Notification(`ParentComm reminder: ${r.studentName}`,{body:r.message})}catch{}toast(`Reminder due: ${r.studentName}`,'success')}if(due.length){save();localStorage.setItem(key,'1')}}
function init(){
 document.documentElement.dataset.theme=state.settings.theme||'light';renderShell();route(app.route);setInterval(reminderWatcher,30000);reminderWatcher();
}
init();
